# Network Data:
version: 1
config:
  - type: physical
    name: enp1s0
    subnets:
      - type: static
        address: 172.16.1.150/16
        gateway: 172.16.0.1
        dns_nameservers:
          - 114.114.114.114
          - 114.114.115.115
---
# User Data:
#cloud-config
password: ubuntu
chpasswd: { expire: False }
ssh_pwauth: True
# 配置阿里云源
apt:
  primary:
    - arches: [default]
      uri: http://mirrors.aliyun.com/ubuntu/
# 配置docker mirror
write_files:
- content: |
      {"registry-mirrors": ["https://fogjl973.mirror.aliyuncs.com"]}
  path: /etc/docker/daemon.json
# 安装docker
packages:
    - docker.io
runcmd:
  - wget https://hailong-work.oss-cn-shenzhen.aliyuncs.com/harvester/configure_rancher_server.sh -O /opt/configure_rancher_server.sh
  - chmod a+x /opt/configure_rancher_server.sh && /opt/configure_rancher_server.sh 172.16.1.150 password v2.5.4
